#pragma once

#define HOLD_ON_OTHER_KEY_PRESS
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 10

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 15

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 10
